version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    restart: always
    depends_on:
      - backend
    volumes:
      - static:/static

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "9000:80"   # хостовый nginx проксирует 443 -> 127.0.0.1:9000
    volumes:
      - static:/static
      - media:/media

volumes:
  static:
  media:
  pg_data:
