services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_started
    volumes:
      - static:/backend_static
      - media:/media
    expose:
      - "8000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    restart: always
    # В проде фронт уже собран внутри образа и слушает 80 порт
    expose:
      - "80"

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    restart: always
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Подменяем конфиг nginx внутри контейнера на наш
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Подключаем сертификаты Let's Encrypt с хоста
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  static:
  media:
  pg_data:
