services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    expose:
      - "80"

  gateway:
    build:
      context: ./nginx
    container_name: gateway
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # локально TLS не нужен — эту строку в dev можно убрать
      # - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  static:
  media:
  pg_data:
