services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_started
    expose:
      - "8000"
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    restart: always
    # В образе фронта статика уже собрана в /usr/share/nginx/html
    volumes:
      - static:/usr/share/nginx/html

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    restart: always
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Статика и медиа, которые собирает backend
      - static:/static
      - media:/media
      # Монтируем РОВНО один конфиг-файл внутрь conf.d
      - ./nginx/default.conf:/etc/nginx/conf.d/100-custom.conf:ro
      # Системные сертификаты Let's Encrypt с хоста (после certbot)
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  static:
  media:
  pg_data:
