version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    # build фронта кладёт файлы в /usr/share/nginx/html внутри образа

  gateway:
    build:
      context: ./nginx
    container_name: gateway
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
      # в dev можно монтировать конфиг nginx и сертификаты (если есть)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pg_data:
  static:
  media:
