version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_started
    expose:
      - "8000"
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    restart: always
    # build фронта уже кладёт файлы в /usr/share/nginx/html внутри образа
    # дополнительные тома НЕ нужны

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    restart: always
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # статика/медиа от Django, чтобы nginx мог их отдавать напрямую
      - static:/static
      - media:/media
      # только сертификаты; nginx.conf в проде уже внутри образа!
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pg_data:
  static:
  media:
