services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - static:/usr/share/nginx/html

  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media

volumes:
  static:
  media:
  pg_data:
