# kittygram_workflow.yml
name: Kittygram compatibility workflow

on:
  push:
    branches: [ "main" ]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Compatibility marker for tests
        run: echo "kittygram_workflow.yml exists for test compatibility"
